version: '3.5'
services:
  client:
    build: client
    restart: unless-stopped
    ports: 
    - "8080:8080"
  server:
    build: server_cpp
    restart: unless-stopped
    ports: 
    - "3000:3000"
